name: Build 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd releng/model.emf.dbusxml.parent
          mvn --batch-mode --update-snapshots clean install
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: "Test Results"
          report_paths: 'plugins/*/target/surefire-reports/*.xml'
          fail_on_failure: true
          summary: true